# Generated by Django 6.0.4 on 2026-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='key',
            field=models.TextField(default=''),
        ),
    ]
