# Generated by Django 6.0.4 on 2026-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_email_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
