# Generated by Django 6.0.4 on 2026-05-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0003_email_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
