# Generated by Django 6.0.4 on 2026-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
