# Generated by Django 6.0.4 on 2026-05-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0008_email_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
