# Generated by Django 6.0.4 on 2026-05-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0011_email_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='encrypted_attachment',
            field=models.FileField(blank=True, null=True, upload_to='encrypted_attachments/'),
        ),
    ]
