# Generated by Django 6.0.4 on 2026-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0013_otp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachment_iv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
