# Generated by Django 6.0.4 on 2026-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0014_email_attachment_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachment_auth_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
