# Generated by Django 6.0.4 on 2026-05-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0016_email_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='all_receivers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
