# Generated by Django 6.0.4 on 2026-05-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0018_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
