# Generated by Django 6.0.4 on 2026-05-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0019_email_is_draft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
