# Generated by Django 6.0.4 on 2026-06-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0020_delete_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
