# Generated by Django 6.0.4 on 2026-07-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0021_loginactivity_is_active_loginactivity_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='SUCCESS', max_length=10),
        ),
    ]
