# Generated by Django 6.0.4 on 2026-07-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0022_loginactivity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]