# Generated by Django 6.0.4 on 2026-07-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0023_userprofile_is_deleted_userprofile_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_mail_id', models.IntegerField()),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('encrypted_message', models.TextField()),
                ('iv', models.TextField()),
                ('auth_tag', models.TextField()),
                ('key', models.TextField()),
                ('key_id', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='deleted_attachments/')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]