# Generated by Django 6.0.7 on 2026-08-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0024_deletedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='deleted_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
